GMAIL_USERNAME: Your_Username
GMAIL_PASSWORD: Your_Password
SUPER_ADMIN_FIRST_NAME: First
SUPER_ADMIN_LAST_NAME: Admin
SUPER_ADMIN_EMAIL: user@example.com
SUPER_ADMIN_PASSWORD: changeme

UNIVERSITY_ADMIN_FIRST_NAME: First
UNIVERSITY_ADMIN_LAST_NAME: University
UNIVERSITY_ADMIN_EMAIL: university@example.com
UNIVERSITY_ADMIN_PASSWORD: changeme

LINKEDIN_API_KEY: 75wjwu8u1wnhrx
LINKEDIN_SECRET_KEY: l2uRE4vx70k6ItRp

ROLES: [super_admin, university_admin, member, club_owner, club_admin, event_admin]

STRIPE_CONNECT_CLIENT_ID: ca_2ylCry8pgU1rO3UYmlmK5JaO7XbfjZaR
STRIPE_SECRET_KEY: sk_test_9i5iZnZWUXtw41plXFDW1KuZ

APPLICATION_FEE: 0.05
